spring:
  profiles:
    active: local
management:
  health:
    defaults:
      enabled: false
elasticsearch:
  index: revu
  alias:
    post: revu_posts
    campaign: revu_campaigns

# gradle.properties
systemProp:
  sonar:
    login: 11d1c24cdcb51323054c66d0c64d16034b3d52d2
    projectKey: 11d1c24cdcb51323054c66d0c64d16034b3d52d2
    host:
      url: http://localhost:9000
---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://db.dello.cc?zeroDateTimeBehavior=convertToNull
    username: revu
    password: f1reInThe$o1e
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.revu.indexer.mapper
  mapper-locations: classpath:mybatis/mapper/**/*.xml

server:
  port: 8081

elasticsearch:
  host: 3.112.180.197
  port: 9200
  type: _doc
  user: revu
  password: revu$R%T^Y
  shards: 2
  replicas: 0

aws:
  s3:
    host: s3.ap-northeast-2.amazonaws.com
    bucket: cmw-ws
    region: ap-northeast-2
    key-name: system/images
    local-file-save-path: ${HOME}

redis:
  host: localhost
  port: 6379
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://db.dello.cc?zeroDateTimeBehavior=convertToNull
    username: revu
    password: f1reInThe$o1e
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.revu.indexer.mapper
  mapper-locations: classpath:mybatis/mapper/**/*.xml

server:
  port: 8081

elasticsearch:
  host: 172.31.13.241
  port: 9200
  type: _doc
  user: revu
  password: revu$R%T^Y
  shards: 2
  replicas: 0

aws:
  s3:
    host: s3.ap-northeast-2.amazonaws.com
    bucket: cmw-ws
    region: ap-northeast-2
    key-name: system/images
    local-file-save-path: ${HOME}

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://weble-aurora-2019-04-28-cluster.cluster-ro-cujdzc5qsvm7.ap-northeast-1.rds.amazonaws.com?zeroDateTimeBehavior=convertToNull
    username: revu
    password: f1reInThe$o1e
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.revu.indexer.mapper
  mapper-locations: classpath:mybatis/mapper/**/*.xml

server:
  port: 8080

elasticsearch:
  host: 172.31.3.42,172.31.3.139
  port: 9200
  type: _doc
  user: revu
  password: revu$R%T^Y
  shards: 2
  replicas: 1

aws:
  s3:
    host: s3.ap-northeast-2.amazonaws.com
    bucket: cmw-ws
    region: ap-northeast-2
    key-name: system/images
    local-file-save-path: ${HOME}
